# Project-wide Gradle settings

# Enable AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin daemon optimization
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m

# Gradle daemon optimization
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Suppress outdated JDK access warnings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED
